baseURL = "https://allincruisive.com"
languageCode = "en-us"
title = "AllinCruisive"
theme = "not-much"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
  description = "a place to store my cruise obsessions"
  mainSections = ["posts"]
  showReadingTime = true

[author]
  name = "Dori"
  homepage = "https://allincruisive.com"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/home/"
  weight = 1

  [[menu.main]]
  name = "My Cruises"
  url = "/my-cruises/"
  weight = 2

  [[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 3

  [[menu.main]]
  name = "Thoughts"
  url = "/thoughts/"
  weight = 4
